---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hubkchx2q0c5/public_html
    - /bin/cp -a . $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/.git
    - /bin/rm -f $DEPLOYPATH/.cpanel.yml
    - /bin/rm -rf $DEPLOYPATH/portal/sql
