---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mssundarakanda/public_html
    - /usr/bin/rsync -rvzp --exclude=".git" --exclude=".gitignore" --exclude=".cpanel.yml" --exclude="portal/sql" ./ $DEPLOYPATH
